roledefs:
  hello:
    - app.docker.local
    - db.docker.local
    - proxy.docker.local
  app:
    - app.docker.local
  db:
    - db.docker.local
  proxy:
    - proxy.docker.local

environment: docker
